version: '3.8'

services:
  pgdb:
    image: postgres:14
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdb_data:/var/lib/postgresql/data

volumes:
  pgdb_data:
